
tclean(vis= 'TDEM0009_Kuband.ms',
       imagename = 'SgrB2_Meth_Ku01',
       field = 'F1-F5',
       spw = 'EVLA_KU#A0C0#23',
       specmode = 'cube',
       nchan = 2048,
       chanchunks= -1,
       start = '0.0km/s',
       width = '0.13km/s',
       outframe='LSRK',
       restfreq = '12177.5337MHz' ,
       deconvolver = 'hogbom',
       gridder = 'standard',
       cell = '0.03arcsec',
       imsize = [8000,8000],
       weighting = 'natural',
       restoringbeam='common',
       niter = 0)

   
tclean(vis= 'TDEM0009_Kuband.ms',
       imagename = 'SgrB2_Form_Ku01',
       field = 'F1-F5',
       spw = 'EVLA_KU#B0D0#41',
       specmode = 'cube',
       nchan = 3840,
       chanchunks= -1,
       start = '0.0km/s',
       width = '0.13km/s',
       outframe='LSRK',
       restfreq = '14.488479GHz',
       deconvolver = 'hogbom',
       gridder = 'standard',
       cell = '0.03arcsec',
       imsize = [8000,8000],
       weighting = 'natural',
       restoringbeam='common',
       niter = 0)


tclean(vis= 'TDEM0009_Kuband.ms',
       imagename = 'CloudC_Meth_Ku01',
       field = 'F6',
       spw = 'EVLA_KU#A0C0#23',
       specmode = 'cube',
       nchan = 2048,
       chanchunks= -1,
       start = '0.0km/s',
       width = '0.13km/s',
       outframe='LSRK',
       restfreq = '12177.5337MHz' ,
       deconvolver = 'hogbom',
       gridder = 'standard',
       cell = '0.03arcsec',
       imsize = [8000,8000],
       weighting = 'natural',
       restoringbeam='common',
       niter = 0)

   
tclean(vis= 'TDEM0009_Kuband.ms',
       imagename = 'CloudC_Form_Ku01',
       field = 'F6',
       spw = 'EVLA_KU#B0D0#41',
       specmode = 'cube',
       nchan = 3840,
       chanchunks= -1,
       start = '0.0km/s',
       width = '0.13km/s',
       outframe='LSRK',
       restfreq = '14.488479GHz',
       deconvolver = 'hogbom',
       gridder = 'standard',
       cell = '0.03arcsec',
       imsize = [8000,8000],
       weighting = 'natural',
       restoringbeam='common',
       niter = 0)




tclean(vis= 'TDEM0009_Kuband.ms',
       imagename = 'SgrC_Meth_Ku01',
       field = 'F7-F8',
       spw = 'EVLA_KU#A0C0#23',
       specmode = 'cube',
       nchan = 2048,
       chanchunks= -1,
       start = '0.0km/s',
       width = '0.13km/s',
       outframe='LSRK',
       restfreq = '12177.5337MHz' ,
       deconvolver = 'hogbom',
       gridder = 'standard',
       cell = '0.03arcsec',
       imsize = [8000,8000],
       weighting = 'natural',
       restoringbeam='common',
       niter = 0)

tclean(vis= 'TDEM0009_Kuband.ms',
       imagename = 'SgrC_Form_Ku01',
       field = 'F7-F8',
       spw = 'EVLA_KU#B0D0#41',
       specmode = 'cube',
       nchan = 3840,
       chanchunks= -1,
       start = '0.0km/s',
       width = '0.13km/s',
       outframe='LSRK',
       restfreq = '14.488479GHz',
       deconvolver = 'hogbom',
       gridder = 'standard',
       cell = '0.03arcsec',
       imsize = [8000,8000],
       weighting = 'natural',
       restoringbeam='common',
       niter = 0)
